email_admin_password = "EM2026"

mail_webhook_url = "https://default8038ed558a654a639fb7969d3fc2b3.dc.environment.api.powerplatform.com:443/powerautomate/automations/direct/workflows/e1e7bb75bd884ff68f414ea140a00ce4/triggers/manual/paths/invoke?api-version=1"
mail_webhook_token = "mi_token_secreto_123"

default_to = "jbreyton@nexwellpower.com, mmoreno@nexwellpower.com"
default_cc = ""
