email_admin_password = "EM2026"

smtp_host = "smtp.office365.com"
smtp_port = "587"
smtp_user = "tu_email@empresa.com"
smtp_password = "tu_password_o_app_password"
smtp_from = "tu_email@empresa.com"

default_to = "jbreyton@nexwellpower.com"
